import { chromium } from "playwright";
const OUT="/tmp/sca-shots", BASE="http://localhost:4319";
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:412,height:900},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const p=await ctx.newPage(); const errs=[], log=[];
p.on("pageerror",e=>errs.push(e.message)); p.on("console",e=>e.type()==="error"&&errs.push(e.text()));
const ok=(c,m)=>log.push((c?"✅":"❌")+" "+m);
await p.goto(BASE+"/",{waitUntil:"networkidle"}); await p.waitForTimeout(2700);
ok(await p.getByText("Bem-vindo ao clube").isVisible().catch(()=>false), "Welcome (login) aparece após splash");
await p.screenshot({path:`${OUT}/wel-login.png`});
await p.getByRole("button",{name:/convidado/i}).click().catch(e=>log.push("conv: "+e.message)); await p.waitForTimeout(600);
ok(await p.getByText("Como prefere ser chamado").isVisible().catch(()=>false), "Passo do nome aparece");
await p.locator("input[placeholder='Seu nome']").fill("José"); await p.waitForTimeout(200);
await p.screenshot({path:`${OUT}/wel-nome.png`});
await p.getByRole("button",{name:/Entrar no clube/i}).click(); await p.waitForTimeout(900);
const greet = await p.locator("h1:has-text('José')").first().isVisible().catch(()=>false);
ok(greet, "App abre e saúda pelo nome");
await p.screenshot({path:`${OUT}/wel-home.png`});
await b.close();
console.log(log.join("\n")); console.log("erros:", errs.length?errs.join("\n"):"NENHUM 🎉");
